debian:
  codenames:
    - stretch
    - buster
    
upstream_projects:
  - name: moonshot-ms-infrastructure
    # branch: <same as this build>
  - name: shibboleth-idp
    # branch: <same as this build>
  - name: psec-sensu-plugins
    branch: v3.12.0
  - name: psec-apache2-config
    branch: v3.12.0
  - name: eapol-test
    branch: v3.12.0
  - name: psec-duo-auth
    branch: v3.12.0


